### ISSUE TITLE
加载块时求值一次

### ISSUE THREAD

**Issue by TCOTC** [2234839/siyuan_expr#2]
> 插件会不断对发生变化的块进行求值，但为了避免产生大量运算和读写，依据块的 update 字段进行了一些优化，在插件初次启动时会对所有表达式进行一次求值，之后只会对更新了的块的表达式进行求值。

> 如果想要触发求值，可以手动随意修改一下块内容。

我有个想法，把这个当作动态的模板来用。

能不能实现打开文档的时候就刷新一下这个块？（或者动态加载出这个块的时候刷新）

还有这一坨 JS 显示在块上面不太美观

![image](https://github.com/2234839/siyuan_expr/assets/78434827/4eee2af5-2176-4fea-ac1d-81cb2560216f)

**Comment by 2234839** [comment]
感谢反馈
1. 作为动态模板也是这个插件的目的之一
2. 关于刷新时机，在动态加载出块的时候进行刷新，我之后添加此功能。
3. js 显示在上方主要是为了表示这是一个 expr 块，之后我改成只展示一行

**Comment by TCOTC** [comment]
> 为了表示这是一个 expr 块

改成在右上角加一个小图标怎么样？

**Comment by 2234839** [comment]
> > 为了表示这是一个 expr 块
> 
> 改成在右上角加一个小图标怎么样？

可以的，但我现在还没想好怎么做，以后会做成可以点击直接弹出编辑框的形式

**Comment by 2234839** [comment]
@88250 发现思源会存在两个不同地方的块，块id一致的情况，然后删除其中一个块后 blocks 中就找不到记录了，需要重建索引才能查询到
我刚刚的触发场景是分屏将块移动过去，然后关闭掉原来的页签，然后我查数据发现不对劲，翻过去看原来页面中还有我刚刚移走的块，他俩 id 一致，但自定义属性的id不一样（偶发，我尝试重复，没有复现）

**Comment by 2234839** [comment]
https://github.com/2234839/siyuan_expr/releases/tag/v0.0.8

另外感谢您的爱发电
