### ISSUE TITLE
思源笔记批量图片ocr求助

### ISSUE THREAD

**Issue by pisceswb** [2234839/siyuan_expr#3]
请问能通过这个技术支持，写一个可以调用quicker本地ocr程序，批量ocr思源图片，并将ocr内容写入图片ocr文本框的插件吗？
![image](https://github.com/2234839/siyuan_expr/assets/104658457/c4735f73-098e-4847-8dbb-f1c46f102706)

**Comment by 2234839** [comment]
直接用quicker遇到什么障碍了

**Comment by 2234839** [comment]
> 请问能通过这个技术支持，写一个可以调用quicker本地ocr程序，批量ocr思源图片，并将ocr内容写入图片ocr文本框的插件吗？ ![image](https://private-user-images.githubusercontent.com/104658457/340882582-c4735f73-098e-4847-8dbb-f1c46f102706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjE3MDcsIm5iZiI6MTcxODc2MTQwNywicGF0aCI6Ii8xMDQ2NTg0NTcvMzQwODgyNTgyLWM0NzM1ZjczLTA5OGUtNDg0Ny04ZGJiLWYxYzQ2ZjEwMjcwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMTQzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmFjZDM4ZmZkZjVlOGNlZjg5YTM5MjgxOGMwOGVkZDBiMGNmZjE3MjhkYWNjMWQzOGRiMjg1ODA1Yjk5MDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WqpzeCc47Kn59ScySxD-ziL32HW99yNi7aNiPYo166A)

quicker 我不太熟，但批量ocr没问题的

**Comment by pisceswb** [comment]
这是quicker ocr的网页，您可以看一下。本地的，好用的ocr程序也可以。当前Tesseract ocr 不能很好的识别部分带有底色的中文PDF截图内容，不能满足我的要求，因此才想找其他ocr。
https://getquicker.net/kc/help/doc/basic-ocr

**Comment by pisceswb** [comment]
或您帮忙训练一下Tesseract ocr ，或教会我训练Tesseract ocr的方法，好像也可以

**Comment by 2234839** [comment]
https://github.com/hiroi-sora/Umi-OCR?tab=readme-ov-file 你看这个软件的 ocr 效果符合你的要求吗

如果觉得效果可以的话，你购买技术支持（微信:ext_00），我去给oceanpress 插件添加上连接 umi 软件批量 ocr 的功能

**Comment by pisceswb** [comment]
可以，辛苦啦。后面使用过程中如果遇到ocr相关的小问题，还麻烦您能帮忙解决一下。

**Comment by 2234839** [comment]
实现完毕： https://github.com/2234839/OceanPress_siyuan_plugin/releases/tag/v0.3.10 

关联： https://github.com/siyuan-note/siyuan/issues/11584#issuecomment-2169263719   @Achuan-2
